module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./node_modules/react-datetime/dist/**/*.{js,jsx,ts,tsx,css}",
    "./node_modules/react-datetime/typings/**/*.{js,jsx,ts,tsx,css}",
    "./node_modules/react-datetime/css/**/*.{js,jsx,ts,tsx,css}",
    "./node_modules/react-datetime/**/*.{js,jsx,ts,tsx,css}",
  ],
  theme: {
    extend: {
      keyframes: {
        slideUpEnter: {
          "0%": {
            opacity: 0,
            transform: "translateY(20px)",
          },
          "100%": {
            opacity: 100,
            transform: "translateY(0px)",
          },
        },
      },
      animation: {
        slideUpEnter: "slideUpEnter .3s ease-in-out",
      },
    },
  },
  plugins: [],
  safelist: [
    "bg-[#fff]",
    "bg-[#111111]",
    "bg-[#e9ecef]",
    "bg-[#111a2e]",
    "bg-[#1b1b1b]",
    "bg-[#3a4759]",
    "bg-[#252525]",
    "bg-[#162138]",
    "bg-[#151515]",
    "text-[#212529]",
    "text-[#111111]",
    "text-[#e3e9f1]",
    "text-[#6c757d]",
    "text-[#bbbbbb]",
    "text-[#93a3b8]",
    "text-[#f5f5f5]",
    "hover:text-[#212529]",
    "hover:text-[#111111]",
    "hover:text-[#e3e9f1]",
    "hover:text-[#6c757d]",
    "hover:text-[#bbbbbb]",
    "hover:text-[#93a3b8]",
    "hover:text-[#f5f5f5]",
    "border-[#e9ecef]",
    "border-[#495057]",
    "border-[#1b1b1b]",
    "border-[#e9ecef]",
    "border-[#273343]",
    "border-[#222]",
    "hover:bg-[#252525]",
    "hover:bg-[#e9ecef]",
    "hover:bg-[#3a4759]",
    "hover:bg-[#1b1b1b]",
  ],
};
